[mysqld]
basedir="C:/myesmp/mysql"
datadir="C:/myesmp/mysql/data"
port=3306
character-set-server=utf8mb4
default_authentication_plugin=mysql_native_password
skip-grant-tables
# Remove skip-grant-tables once initial setup is done!
